PATH:
  IMAGE_MASK:
    GROUPED: D:\Hepatocyte\image_mask\grouped
    STEATOSIS_2K: D:\Hepatocyte\image_mask\steatosis_2K
  JSON:
    ORIGINAL: D:\Hepatocyte\json\raw
    FIXED: D:\Hepatocyte\json\fixed
    GROUPED: D:\Hepatocyte\json\grouped
    STEATOSIS: D:\Hepatocyte\json\steatosis
    STEATOSIS_2K: D:\Hepatocyte\json\steatosis_2K
  PATCHES:
    GROUPED:
      IMAGE: D:\Hepatocyte\patches\grouped_128\image
      MASK: D:\Hepatocyte\patches\grouped_128\mask
    STEATOSIS:
      IMAGE: D:\Hepatocyte\patches\steatosis_128\image
      MASK: D:\Hepatocyte\patches\steatosis_128\mask
TRAIN:
  MODEL:
    architecture: PSPNet  # Available architectures: https://smp.readthedocs.io/en/latest/models.html
    encoder_name: resnet34  # Available encoders: https://smp.readthedocs.io/en/latest/encoders.html
    output_classes: 1  # Number of classes
  LOSS:
    function: dice
    mode: binary  # Variants: binary, multiclass
  OPTIMIZER: Adam
  LEARNING_RATE: 0.0003
  N_EPOCHS: 10
  BATCH_SIZE: 8