PATH:
  ROOT:                 D:\Hepatocyte_full
  PATCHES:              patches
TRAIN:
  MODEL:
    architecture:       unet  # Available architectures: https://smp.readthedocs.io/en/latest/models.html
    kwargs:
      # Segmentation-model-pytorch framework
      encoder_name:     resnet18  # Available encoders: https://smp.readthedocs.io/en/latest/encoders.html
      encoder_weights:  imagenet # Keep blank for random initialization, or use available weights:
                                 # https://segmentation-models-pytorch.readthedocs.io/en/latest/encoders.html
      classes:          8  # Number of classes
  LOSS:
    function:           tversky  # Available: dice, cross_entropy, soft_cross_entropy, jaccard, focal, tversky
    kwargs:
      mode:             multiclass  # Available: binary, multiclass. Use for dice, jaccard and focal losses
      from_logits:      True
      alpha:            0.5
      beta:             1.0
      class_weights:    # Available for SoftCrossEntropy loss
        0:              0.13646285713814726,
        1:              158.12445963607118,
        2:              26.517137317710528,
        3:              23.70734795387746,
        4:              2.320185217829355,
        5:              7.941571638109712,
        6:              37.22182386141777,
        7:              500.912101910828
  METRICS:
    reduction:          micro
  OPTIMIZER:            AdamW
  SCHEDULER:
    function:           cosine_annealing
    kwargs:
      T_max:            10
  LEARNING_RATE:        0.0003
  N_EPOCHS:             5
  BATCH_SIZE:           8
  PATCH_SIZE:           512
WANDB:
  IDX2LABEL:  # index to label mapping for grouped data
    0: background
    1: hepatocyte_balloon_dystrophy
    2: hepatocyte_inclusion
    3: hepatocyte_non_nuclei
    4: hepatocyte_relatively_normal
    5: hepatocyte_steatosis
    6: mesenchymal_cells
    7: hepatocyte_steatosis_non_nuclei
  PROJECT:  hepatocyte-segmentation
  NAME:     manet-resnet152