PATH:
  ROOT: D:\Hepatocyte_full
  PATCHES: patches
TRAIN:
  MODEL:
    architecture:     unet  # Available architectures: https://smp.readthedocs.io/en/latest/models.html
    encoder_name:     efficientnet-b3  # Available encoders: https://smp.readthedocs.io/en/latest/encoders.html
    encoder_weights:  imagenet # Keep blank for random initialization, or use available weights:
                               # https://segmentation-models-pytorch.readthedocs.io/en/latest/encoders.html
    output_classes:   7  # Number of classes
  LOSS:
    function:         tversky  # Available loss functions: dice, cross_entropy, soft_cross_entropy, jaccard, focal, tversky
    kwargs:
      mode:           multiclass  # Available modes: binary, multiclass. Use for dice, jaccard and focal losses
      from_logits:    True
      alpha:          0.5
      beta:           1.0
  METRICS:
    reduction:        macro
  OPTIMIZER:          AdamW
  SCHEDULER:
    function:         cosine_annealing
    kwargs:
      T_max:          10
  LEARNING_RATE:      0.0003
  N_EPOCHS:           5
  BATCH_SIZE:         8
  PATCH_SIZE:         512
WANDB:
  IDX2LABEL:  # index to label mapping for grouped data
    0: background
    1: hepatocyte_balloon_dystrophy
    2: hepatocyte_inclusion
    3: hepatocyte_non_nuclei
    4: hepatocyte_relatively_normal
    5: hepatocyte_steatosis
    6: mesenchymal_cells
  PROJECT:  hepatocyte-segmentation
  NAME:     unet-efficientnet-b3